language: python
python:
  - 2.7
  - 3.6
env:
  matrix:
    - ETCD3_VERSION=v3.3.9  ETCD3_TLS=""   ETCD3_USER=""
    - ETCD3_VERSION=v3.3.9  ETCD3_TLS=yes  ETCD3_USER=""
    - ETCD3_VERSION=v3.3.9  ETCD3_TLS=yes  ETCD3_USER=test

before_install:
  - ./scripts/etcd_start.sh
  - sleep 5
  - ./scripts/etcd_init.sh

install:
  - pip install -e .
  - pip install nose coverage coveralls

script:
  - nosetests -v --with-coverage --cover-package=etcd3

after_success:
  - coveralls

after_script:
  - ./script/etcd_stop.sh
