language: python
python:
  - 2.7
  - 3.6
env:
  global:
    ETCD3_VERSION=v3.2.23

before_install:
  - ./scripts/etcd_start.sh
  - ./vagrant/etcd_init.sh

install:
  - pip install -e .
  - pip install nose coverage coveralls

script:
  - nosetests --with-coverage --cover-package=etcd3

after_success:
  - coveralls

after_script:
  - ./script/etcd_stop.sh
